language: ruby
script:   bundle exec rake
cache:    bundler
sudo:     false

before_install:
  - gem update --system
  - gem pristine bundler

rvm:
  - 2.0.0
  - 2.1
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
  - jruby-9.1.15.0
  - jruby-head

gemfile:
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_51.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_51.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.2.9
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.3.6
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails_41.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_41.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_32.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_40.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_41.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.15.0
    - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile
    - gemfile: gemfiles/rails_32.gem
